#!/bin/bash

BASE="$(dirname "$(readlink -f "$0")")"
source "$BASE/lib/lib_cmd.sh"

cmd="$1"
shift

set -e

set -a

HCM_HOME="$HOME/.hcm"
MAIN_CONFIG="$HCM_HOME/config.yml"
MODULE_CONFIG="module.yml"
HCM_INSTALLED_MODULES_ROOT="$HCM_HOME/installed_modules"

set +a

if is_valid_cmd_name "$cmd" && [ -f "$BASE/lib/cmd_$(cmd_to_filename "$cmd").sh" ]; then
  bash "$BASE/lib/cmd_$(cmd_to_filename "$cmd").sh" "$@"
else
  bash "$BASE/lib/cmd_help.sh" "$cmd"
fi
